sudo: required

language: java

services:
  - docker

env:
  - JAVAVER="openjdk1.8"
  - JAVAVER="openjdk1.8-devel"

before_install:
  - docker -v

install:
  - make BUILDARGS="--build-arg JAVAVER=$JAVAVER --build-arg USER_ID=$UID"

script:
  - ./runtest.sh
